version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb  
    depends_on:
      - "mongodb"
  my-app:
    image: 401602273424.dkr.ecr.us-east-1.amazonaws.com/my-app:1.0
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - "mongo-express"
  # my-app:
  #   image: my-app:1.0
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - "mongo-express"
volumes:
  mongo-data:
    driver: local
